version: '3'
services:
  backend:
    build:
      context: ./web-crawler-api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./web-crawler-ui
      dockerfile: Dockerfile
    ports:
      - 4000:4000